import XCTest

@testable import KittermCLI

/// Guards the QoS class of the launchd job.
///
/// `ProcessType` is not cosmetic here. launchd applies it as a QoS clamp, and
/// every pane, shell, and coding agent the daemon forks inherits it — so
/// `Background` pins the whole tree to the efficiency cores. Measured on an M4
/// Pro, a fixed CPU benchmark ran ~1.9s under a `Background` job against ~0.39s
/// under an `Interactive` one, with the `Background` samples also scattering
/// (1.5-2.3s) where the `Interactive` ones held flat. It reached users as slow
/// tab creation, keystroke lag, and long-running commands.
///
/// The key sat inert in the plist for months because `kitterm start` used to
/// fork the daemon from the calling shell, which inherited that shell's QoS.
/// Rooting the daemon at launchd made it live. That is why this is asserted
/// rather than left to review: nothing about the daemon's own CPU use hints at
/// it, and the cost only appears once launchd owns the process.
final class LaunchdPlistTests: XCTestCase {
    private func plist(keepAlive: Bool) throws -> [String: Any] {
        let body = KittermMain.launchdPlistBody(
            executable: "/usr/local/lib/kitterm/kitterm",
            port: 3418,
            flags: DaemonFlags(),
            keepAlive: keepAlive
        )
        let data = try XCTUnwrap(body.data(using: .utf8))
        let parsed = try PropertyListSerialization.propertyList(
            from: data,
            options: [],
            format: nil
        )
        return try XCTUnwrap(parsed as? [String: Any])
    }

    /// Both launchd jobs come from this one body: the session job that
    /// `kitterm start` bootstraps (keepAlive false) and the LaunchAgent that
    /// `kitterm service install` writes (keepAlive true). Neither may be
    /// throttled, so both are checked.
    func testNeitherJobRunsAtBackgroundQoS() throws {
        for keepAlive in [true, false] {
            let processType = try plist(keepAlive: keepAlive)["ProcessType"] as? String
            XCTAssertEqual(
                processType,
                "Interactive",
                """
                launchd ProcessType must be Interactive (keepAlive: \(keepAlive)). \
                Background clamps the daemon and every pane it forks to the \
                efficiency cores — roughly a 5x slowdown on Apple silicon.
                """
            )
        }
    }

    /// The plist is generated by string interpolation, so a malformed entry
    /// would only surface as a `launchctl bootstrap` failure at run time.
    /// Parsing it here keeps that failure at build time, and confirms the
    /// arguments the job is actually launched with.
    func testGeneratedPlistParsesAndCarriesTheServeCommand() throws {
        let session = try plist(keepAlive: false)
        XCTAssertEqual(session["Label"] as? String, "com.kitterm.daemon")
        XCTAssertEqual(session["RunAtLoad"] as? Bool, true)
        XCTAssertEqual(session["KeepAlive"] as? Bool, false)
        XCTAssertEqual(
            session["ProgramArguments"] as? [String],
            ["/usr/local/lib/kitterm/kitterm", "serve", "--port", "3418"]
        )

        // `kitterm service install` is the only one that should resurrect
        // itself; `kitterm start` has never restarted a daemon that exited.
        XCTAssertEqual(try plist(keepAlive: true)["KeepAlive"] as? Bool, true)
    }
}
